# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Framework

on:
  push:
    branches: [ "dev", "fix-cli-net-framework" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Restore Packages
        run: nuget restore Naticord/Naticord.sln
      - name: Build
        run: 'msbuild Naticord/Naticord.sln -t:rebuild -property:Configuration=Release'
      - name: Upload Rectify11Installer
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Naticord
          path: Naticord\bin\Debug\*
          compression-level: 0
